# =============================================================================
# build.ps1 - AGFA-MON ROM build for Agfa Compugraphic 9000PS (PowerShell)
# =============================================================================
#
# USAGE
#   From agfa-monitor directory:
#     .\build.ps1
#
#   From project root:
#     .\agfa-monitor\build.ps1
#
# WHAT IT DOES
#   1. Generates include/build_version.inc with current timestamp
#   2. Assembles agfa-mon.m68 -> agfa-rom.bin (128KB flat binary)
#   3. Splits agfa-rom.bin -> four 32KB EPROM images (HH/HM/LM/LL)
#
# =============================================================================

param(
    [Switch]$Chips,    # Alias for 'build chips only' (same as no args)
    [Switch]$Clean,    # Delete generated files
    [Switch]$Help      # Show help
)

# =============================================================================
# Configuration
# =============================================================================

$ProjectRoot = Split-Path -Parent (Split-Path -Parent (Get-Location))
$AgfaMonDir = Join-Path $ProjectRoot "agfa-monitor"
$AssemblerDir = Join-Path $ProjectRoot "assembler"
$IncludeDir = Join-Path $AgfaMonDir "include"

# Tool paths
$Vasm = Join-Path $AssemblerDir "vasmm68k_mot.exe"
$Python = "python"  # Assumes python is in PATH; adjust if needed
$SplitRom = Join-Path $AssemblerDir "split_rom.py"

# Source files
$MonSrc = Join-Path $AgfaMonDir "agfa-mon.m68"
$EhBasicInc = Join-Path $AgfaMonDir "ehbasic68k.inc"
$VersionInc = Join-Path $IncludeDir "build_version.inc"

# Include files that trigger rebuilds if changed
$Includes = @(
    Join-Path $IncludeDir "nvram_config.inc",
    Join-Path $IncludeDir "vera_init.inc",
    Join-Path $IncludeDir "vera_text.inc",
    Join-Path $IncludeDir "vera_cursor.inc",
    Join-Path $IncludeDir "via_timer.inc"
)

# Output files
$RomBin = Join-Path $AgfaMonDir "agfa-rom.bin"
$RomLst = Join-Path $AgfaMonDir "agfa-rom.lst"
$ChipHH = Join-Path $AgfaMonDir "agfa-rom-HH.bin"
$ChipHM = Join-Path $AgfaMonDir "agfa-rom-HM.bin"
$ChipLM = Join-Path $AgfaMonDir "agfa-rom-LM.bin"
$ChipLL = Join-Path $AgfaMonDir "agfa-rom-LL.bin"
$Chips = @($ChipHH, $ChipHM, $ChipLM, $ChipLL)

# =============================================================================
# Functions
# =============================================================================

function Show-Help {
    Write-Host ""
    Write-Host "AGFA-MON ROM build (PowerShell)"
    Write-Host ""
    Write-Host "  .\build.ps1          Build everything (assemble + split)"
    Write-Host "  .\build.ps1 -Chips   Same as above"
    Write-Host "  .\build.ps1 -Clean   Remove agfa-rom.bin and the four chip files"
    Write-Host "  .\build.ps1 -Help    This message"
    Write-Host ""
    Write-Host "Assembler: $Vasm"
    Write-Host "Python:    $Python"
    Write-Host ""
}

function Test-Tools {
    $AllGood = $true

    if (-not (Test-Path $Vasm)) {
        Write-Host "ERROR: vasm assembler not found at: $Vasm" -ForegroundColor Red
        $AllGood = $false
    }

    if (-not (Test-Path $SplitRom)) {
        Write-Host "ERROR: split_rom.py not found at: $SplitRom" -ForegroundColor Red
        $AllGood = $false
    }

    try {
        $null = & $Python --version 2>&1
    } catch {
        Write-Host "ERROR: Python not found in PATH" -ForegroundColor Red
        $AllGood = $false
    }

    return $AllGood
}

function Test-SourceFiles {
    $AllGood = $true

    if (-not (Test-Path $MonSrc)) {
        Write-Host "ERROR: Source file not found: $MonSrc" -ForegroundColor Red
        $AllGood = $false
    }

    if (-not (Test-Path $EhBasicInc)) {
        Write-Host "ERROR: EhBASIC include not found: $EhBasicInc" -ForegroundColor Red
        Write-Host "       This file should be checked in. To regenerate, see Makefile comments." -ForegroundColor Yellow
        $AllGood = $false
    }

    foreach ($inc in $Includes) {
        if (-not (Test-Path $inc)) {
            Write-Host "ERROR: Include file not found: $inc" -ForegroundColor Red
            $AllGood = $false
        }
    }

    return $AllGood
}

function New-VersionInclude {
    Write-Host ""
    Write-Host "[Step 0/2] Generating build version..."

    $Timestamp = Get-Date -Format "dd-MMM-yyyy HH:mm"
    $VersionString = "BUILD $Timestamp"

    $VersionContent = @(
        "; auto-generated by build.ps1 -- do not edit",
        "STR_BUILD_VERSION:",
        "        DC.B    ""$VersionString"",`$0D,`$0A,0",
        "        ALIGN   2"
    ) -join "`n"

    # Ensure directory exists
    $null = New-Item -ItemType Directory -Force -Path $IncludeDir

    Set-Content -Path $VersionInc -Value $VersionContent -Encoding ASCII
    Write-Host "        Version: $VersionString"
    Write-Host "        Written to: $VersionInc"
}

function Invoke-Assembler {
    Write-Host ""
    Write-Host "[Step 1/2] Assembling $([System.IO.Path]::GetFileName($MonSrc))..."
    Write-Host "           (running vasm from project root -- required for INCBIN paths)"

    Push-Location $ProjectRoot

    try {
        $Output = & $Vasm -m68020 -Fbin `
            -L "agfa-monitor/$([System.IO.Path]::GetFileName($RomLst))" `
            -o "agfa-monitor/$([System.IO.Path]::GetFileName($RomBin))" `
            "agfa-monitor/$([System.IO.Path]::GetFileName($MonSrc))" 2>&1

        if ($LASTEXITCODE -ne 0) {
            Write-Host "ERROR: Assembly failed" -ForegroundColor Red
            Write-Host $Output
            return $false
        }

        Write-Host $Output

        if (Test-Path $RomBin) {
            $Size = (Get-Item $RomBin).Length
            Write-Host "        ROM binary: $Size bytes"
            Write-Host "        Assembly complete."
        } else {
            Write-Host "ERROR: Assembly produced no output file" -ForegroundColor Red
            return $false
        }
    } finally {
        Pop-Location
    }

    return $true
}

function Invoke-RomSplit {
    Write-Host ""
    Write-Host "[Step 2/2] Splitting $([System.IO.Path]::GetFileName($RomBin)) into EPROM images..."

    $Output = & $Python $SplitRom $RomBin 2>&1

    if ($LASTEXITCODE -ne 0) {
        Write-Host "ERROR: ROM split failed" -ForegroundColor Red
        Write-Host $Output
        return $false
    }

    Write-Host ""
    Write-Host "EPROM images ready:"
    Write-Host "  $([System.IO.Path]::GetFileName($ChipHH))  ->  D24-D31  (MSB)  -- program into HH socket"
    Write-Host "  $([System.IO.Path]::GetFileName($ChipHM))  ->  D16-D23          -- program into HM socket"
    Write-Host "  $([System.IO.Path]::GetFileName($ChipLM))  ->  D8-D15           -- program into LM socket"
    Write-Host "  $([System.IO.Path]::GetFileName($ChipLL))  ->  D0-D7    (LSB)  -- program into LL socket"
    Write-Host ""
    Write-Host "Programmer: TL866-3G, AM27C256 mode, A0-A14 (32K each chip)"
    Write-Host "Serial:     Z85C30 Ch A, DE-9 RS-232, 9600 8N1"
    Write-Host ""

    return $true
}

function Invoke-Clean {
    Write-Host "Removing generated files..."

    @($RomBin, $RomLst, $ChipHH, $ChipHM, $ChipLM, $ChipLL, $VersionInc) | ForEach-Object {
        if (Test-Path $_) {
            Remove-Item $_ -Force
            Write-Host "  Deleted: $([System.IO.Path]::GetFileName($_))"
        }
    }

    Write-Host "Done.  (ehbasic68k.inc kept -- it is checked-in source)"
}

# =============================================================================
# Main
# =============================================================================

if ($Help) {
    Show-Help
    exit 0
}

if ($Clean) {
    Invoke-Clean
    exit 0
}

# Default: build everything
Write-Host ""
Write-Host "AGFA-MON ROM Build"
Write-Host "=================="

# Verify tools and sources
if (-not (Test-Tools)) {
    Write-Host ""
    Write-Host "ERROR: Required tools not found. Please verify installation." -ForegroundColor Red
    exit 1
}

if (-not (Test-SourceFiles)) {
    Write-Host ""
    Write-Host "ERROR: Required source files not found." -ForegroundColor Red
    exit 1
}

# Generate build version
New-VersionInclude

# Assemble
if (-not (Invoke-Assembler)) {
    exit 1
}

# Split ROM
if (-not (Invoke-RomSplit)) {
    exit 1
}

Write-Host "Build successful!"
exit 0
